package io.github.jaymcole.housegraph.plugin;

import io.github.jaymcole.housegraph.logging.Log;
import io.github.jaymcole.housegraph.logging.Logger;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.regex.Pattern;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

/**
 * A node library's self-description, read from {@value #ENTRY} inside its jar.
 *
 * <h2>Why a JSON resource rather than a service provider</h2>
 * A {@code ServiceLoader} provider interface would be typed, and it is the precedent this
 * repository already sets for the SLF4J binding. It was rejected anyway, for one decisive reason:
 * reading it requires <em>loading and linking a class</em>. The single most important job this
 * metadata has is explaining why a library could not be loaded — a library compiled against a
 * different API version whose provider class throws {@code NoClassDefFoundError} on link would
 * leave nothing to show the user but a stack trace. Metadata has to be readable from a jar you
 * have decided not to trust with your class loader. {@code MANIFEST.MF} attributes were rejected
 * too: readable without class loading, but flat strings only, and {@code nodePackages} is a list.
 *
 * <p>Reads are forgiving in the same style as {@code AppPreferences.loadFrom}: a jar that is
 * missing the entry, or whose entry is corrupt, yields {@link Optional#empty()} and a log line
 * rather than an exception. A jar without a valid manifest is simply not a node library.
 */
public record PluginManifest(int manifestVersion,
                             String id,
                             String name,
                             String version,
                             String apiVersion,
                             String repository,
                             String description,
                             List<String> nodePackages,
                             String categoryPrefix) {

    private static final Logger log = Log.get(PluginManifest.class);

    /** Where a node library declares itself. Generated by its build, never hand-written. */
    public static final String ENTRY = "META-INF/housegraph-plugin.json";

    /** The manifest schema this build understands. */
    public static final int SUPPORTED_MANIFEST_VERSION = 1;

    /**
     * The id doubles as a directory name and a save-file key, so it is deliberately narrow: it must
     * survive {@code AppDirectories.sanitize} unchanged and be recognisable in a JSON file.
     */
    private static final Pattern VALID_ID = Pattern.compile("[a-z0-9][a-z0-9._-]*");

    /**
     * Reads a jar's manifest without opening a class loader on it.
     *
     * @param jar the jar to inspect
     * @return the manifest, or empty if absent, unreadable, or invalid
     */
    public static Optional<PluginManifest> read(Path jar) {
        try (ZipFile zip = new ZipFile(jar.toFile())) {
            ZipEntry entry = zip.getEntry(ENTRY);
            if (entry == null) {
                log.warn("{} has no {} — it is not a HouseGraph node library", jar.getFileName(), ENTRY);
                return Optional.empty();
            }
            try (InputStream in = zip.getInputStream(entry)) {
                String text = new String(in.readAllBytes(), StandardCharsets.UTF_8);
                return parse(new JSONObject(text));
            }
        } catch (IOException | JSONException e) {
            log.warn("Could not read {} from {}: {}", ENTRY, jar, e.toString());
            return Optional.empty();
        }
    }

    /**
     * Validates and builds a manifest from already-parsed JSON. Separate from {@link #read} so the
     * validation rules can be tested without building a jar.
     *
     * @param json the parsed manifest
     * @return the manifest, or empty if it fails validation (with the reason logged)
     */
    static Optional<PluginManifest> parse(JSONObject json) {
        int manifestVersion = json.optInt("manifestVersion", 1);
        if (manifestVersion > SUPPORTED_MANIFEST_VERSION) {
            log.warn("Node library manifest version {} is newer than this build understands ({})",
                    manifestVersion, SUPPORTED_MANIFEST_VERSION);
            return Optional.empty();
        }

        String id = json.optString("id", "").trim();
        if (!VALID_ID.matcher(id).matches()) {
            log.warn("Node library manifest has an invalid id \"{}\"; must match {}", id, VALID_ID.pattern());
            return Optional.empty();
        }

        List<String> nodePackages = stringList(json.optJSONArray("nodePackages"));
        if (nodePackages.isEmpty()) {
            log.warn("Node library \"{}\" declares no nodePackages, so nothing in it could ever be found", id);
            return Optional.empty();
        }

        String version = json.optString("version", "").trim();
        if (version.isEmpty()) {
            log.warn("Node library \"{}\" declares no version", id);
            return Optional.empty();
        }

        return Optional.of(new PluginManifest(
                manifestVersion,
                id,
                orDefault(json.optString("name", ""), id),
                version,
                json.optString("apiVersion", "").trim(),
                emptyToNull(json.optString("repository", "")),
                json.optString("description", ""),
                nodePackages,
                // Defaults to the id so a library's nodes always land under one submenu rather than
                // scattering through the top level of the Add-Node menu.
                orDefault(json.optString("categoryPrefix", ""), id)));
    }

    private static List<String> stringList(JSONArray array) {
        List<String> values = new ArrayList<>();
        if (array == null) {
            return values;
        }
        for (int i = 0; i < array.length(); i++) {
            String value = array.optString(i, "").trim();
            if (!value.isEmpty()) {
                values.add(value);
            }
        }
        return values;
    }

    private static String orDefault(String value, String fallback) {
        return value == null || value.isBlank() ? fallback : value.trim();
    }

    private static String emptyToNull(String value) {
        return value == null || value.isBlank() ? null : value.trim();
    }
}
